Integration tests
IoFinnet/reusable-workflows pull request #19
Opened 2023-03-10 14:17 UTC by awls99

This adds the possibility of calling integration tests in the pipeline

2023-03-10 14:28 UTC, BrianArch96 requested changes
just a small question

2023-03-10 14:28 UTC, BrianArch96 commented on .github/workflows/deploy.yaml
> +        default: "18.x"
i can't remember why but I believe @cbarlow1993 is wary of bumping to v18 in some places, gonna tag him so hes aware of this.

2023-03-10 14:28 UTC, BrianArch96 commented on .github/workflows/deploy.yaml
> +        run: npm run test:integration
is this replacing what we've previously used as `test:stage`?

2023-03-10 15:19 UTC, awls99 commented on .github/workflows/deploy.yaml
> +        run: npm run test:integration
This is not replacing, there's a new thing we can use

2023-03-10 15:20 UTC, BrianArch96 commented on .github/workflows/deploy.yaml
> +        run: npm run test:integration
so what is the difference between this and `test:stage`? As that is our current command for calling integration tests

2023-03-10 15:33 UTC, awls99 commented on .github/workflows/deploy.yaml
> +        run: npm run test:integration
Two things: 
one `test:integration` is a way better name (I was genuinely convinced that `test:stage` was testing staging environment)
And, jokes aside, this just makes it so integration tests run after the deploy.
If we're attached to the `test:stage` name 🤷 we can keep it, but I've been seeing `test:integration` on newer PR's

2023-03-13 16:13 UTC, BrianArch96 approved these changes

2023-03-13 16:13 UTC, merged